common:
  debug: false
  root-dir: .
  user: bookandmusic
  user-home: /home/bookandmusic
  env-file: /home/bookandmusic/.zprofile
  cache-dir: cache
  github-proxy: ""
  http-proxy: ""
ansible:
  base-dir: ansible
  python-dir: ansible/python
  ansible-dir: ansible/ansible
python:
  base-dir: python
  versions: []
  global: ""
go:
  base-dir: go
  versions: []
  global: ""
